version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: pintool-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - ../.env
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-postgresql-datasource
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - grafana-network

volumes:
  grafana-data:

networks:
  grafana-network:
    driver: bridge
