apiVersion: 1

datasources:
  - name: Supabase PostgreSQL
    type: postgres
    url: oozbozwzasqrxebomucm.supabase.co:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: '$SUPABASE_DB_PASSWORD'
    jsonData:
      sslmode: require
      postgresVersion: 1300
      timescaledb: false
    isDefault: true
    editable: true
